/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uptackomsai.chatupt.gui;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import uptackomsai.chatupt.utils.ImageLoader;

/**
 *
 * @author Lei
 */
public class MessagePanel extends javax.swing.JPanel {

    /**
     * Creates new form MessagePanel
     * @param profile_path
     * @param content
     * @param username
     * @param time_sent
     * @param is_read
     * @param file_path
     */
    public MessagePanel(String profile_path, String username, String time_sent, 
            String content, String file_path, boolean is_read) { 
        initComponents();
        
        messageTextArea.setText(content);
        usernameLabel.setText(username);
        timestampLabel.setText(time_sent);
        if(is_read) messageStatusLabel.setText("Message Read");
        else messageStatusLabel.setText("Message Delivered");
        if(file_path!=null)
            attachmentPane.setText("<html>Attachment: <a href='" + file_path + "'>" + file_path + "</a></html>");
        
        profilePicLabel.setIcon(new ImageIcon(
            ImageLoader.loadImageIcon(profile_path).getImage().getScaledInstance(
            profilePicLabel.getPreferredSize().width,
            profilePicLabel.getPreferredSize().height,
            Image.SCALE_SMOOTH)
        ));
        
        // For dynamic height
        int calculatedHeight = calculateTextAreaHeight(content, 510);
        this.setPreferredSize(new Dimension(550,calculatedHeight+66));

    }
    
    @Override
    public Dimension getMaximumSize() {
        // Restrict the maximum size of this panel
        return new Dimension(getPreferredSize().width,getPreferredSize().height);
    }
    
    private int calculateTextAreaHeight(String text, int maxWidth) {
        // Get the FontMetrics for the JTextArea
        FontMetrics fontMetrics = messageTextArea.getFontMetrics(messageTextArea.getFont());

        // Calculate the width of the text
        int textWidth = fontMetrics.stringWidth(text);

        // Calculate the number of lines required
        int lines = (int) Math.ceil((double) textWidth / maxWidth);

        // Calculate the total height based on line height
        int lineHeight = fontMetrics.getHeight();
        return lines * lineHeight;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePanel = new javax.swing.JPanel();
        profilePicLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        headcontentPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        timestampLabel = new javax.swing.JLabel();
        bodycontentPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        messageTextArea = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        footcontentPanel = new javax.swing.JPanel();
        messageStatusLabel = new javax.swing.JLabel();
        attachmentPanel = new javax.swing.JPanel();
        attachmentPane = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        profilePanel.setLayout(new java.awt.BorderLayout());

        profilePicLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        profilePicLabel.setPreferredSize(new java.awt.Dimension(40, 40));
        profilePanel.add(profilePicLabel, java.awt.BorderLayout.PAGE_START);

        add(profilePanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setLayout(new java.awt.BorderLayout());

        headcontentPanel.setPreferredSize(new java.awt.Dimension(360, 30));
        headcontentPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        usernameLabel.setText("<username>");
        headcontentPanel.add(usernameLabel);

        timestampLabel.setText("<timestamp>");
        headcontentPanel.add(timestampLabel);

        contentPanel.add(headcontentPanel, java.awt.BorderLayout.PAGE_START);

        bodycontentPanel.setLayout(new java.awt.BorderLayout());
        bodycontentPanel.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setLineWrap(true);
        messageTextArea.setRows(5);
        messageTextArea.setWrapStyleWord(true);
        messageTextArea.setBorder(null);
        messageTextArea.setFocusable(false);
        bodycontentPanel.add(messageTextArea, java.awt.BorderLayout.CENTER);
        bodycontentPanel.add(jSeparator2, java.awt.BorderLayout.PAGE_END);

        contentPanel.add(bodycontentPanel, java.awt.BorderLayout.CENTER);

        footcontentPanel.setPreferredSize(new java.awt.Dimension(360, 20));
        footcontentPanel.setLayout(new java.awt.BorderLayout());

        messageStatusLabel.setText("<message_status>");
        footcontentPanel.add(messageStatusLabel, java.awt.BorderLayout.EAST);

        attachmentPanel.setLayout(new java.awt.BorderLayout());

        attachmentPane.setEditable(false);
        attachmentPane.setContentType("text/html"); // NOI18N
        attachmentPane.setEnabled(false);
        attachmentPanel.add(attachmentPane, java.awt.BorderLayout.CENTER);

        footcontentPanel.add(attachmentPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.add(footcontentPanel, java.awt.BorderLayout.PAGE_END);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane attachmentPane;
    private javax.swing.JPanel attachmentPanel;
    private javax.swing.JPanel bodycontentPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel footcontentPanel;
    private javax.swing.JPanel headcontentPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel messageStatusLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profilePicLabel;
    private javax.swing.JLabel timestampLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
