/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uptackomsai.chatupt.gui;

/**
 *
 * @author Lei
 */
public class ProfileManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfileFrame
     */
    public ProfileManageFrame() {
        initComponents();
        setTitle("ChatUPT");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profilepicPanel = new javax.swing.JPanel();
        profilepicPreview = new javax.swing.JPanel();
        profilepicLabel = new javax.swing.JLabel();
        profilepicButton = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        currentpassPanel = new javax.swing.JPanel();
        currentpassLabel = new javax.swing.JLabel();
        currentpassField = new javax.swing.JPasswordField();
        newpassPanel = new javax.swing.JPanel();
        newpassLabel = new javax.swing.JLabel();
        newpassField = new javax.swing.JPasswordField();
        newpass2Panel = new javax.swing.JPanel();
        newpass2Label = new javax.swing.JLabel();
        newpass2Field = new javax.swing.JPasswordField();
        emailPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        actionsPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel1.setText("Profile Management");
        headPanel.add(jLabel1);

        getContentPane().add(headPanel, java.awt.BorderLayout.PAGE_START);

        profilepicPreview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profilepicPreview.setToolTipText("");
        profilepicPreview.setLayout(new java.awt.BorderLayout());

        profilepicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilepicLabel.setText("<profile pic>");
        profilepicLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        profilepicPreview.add(profilepicLabel, java.awt.BorderLayout.CENTER);

        profilepicButton.setText("Change");
        profilepicButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profilepicButton.setPreferredSize(new java.awt.Dimension(100, 23));
        profilepicButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        profilepicPreview.add(profilepicButton, java.awt.BorderLayout.SOUTH);

        profilepicPanel.add(profilepicPreview);

        getContentPane().add(profilepicPanel, java.awt.BorderLayout.CENTER);

        inputPanel.setPreferredSize(new java.awt.Dimension(400, 240));
        inputPanel.setLayout(new java.awt.GridLayout(6, 1));

        usernamePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        usernameLabel.setText("Username");
        usernamePanel.add(usernameLabel);

        usernameTextField.setText("Current Username");
        usernameTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        usernamePanel.add(usernameTextField);

        inputPanel.add(usernamePanel);

        currentpassPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        currentpassLabel.setText("Current Password");
        currentpassPanel.add(currentpassLabel);

        currentpassField.setText("Current Password");
        currentpassField.setToolTipText("Enter Your Password");
        currentpassField.setPreferredSize(new java.awt.Dimension(250, 30));
        currentpassPanel.add(currentpassField);

        inputPanel.add(currentpassPanel);

        newpassPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        newpassLabel.setText("New Password");
        newpassPanel.add(newpassLabel);

        newpassField.setText("Current Password");
        newpassField.setToolTipText("Enter New Password");
        newpassField.setPreferredSize(new java.awt.Dimension(250, 30));
        newpassPanel.add(newpassField);

        inputPanel.add(newpassPanel);

        newpass2Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        newpass2Label.setText("Confirm New Password");
        newpass2Panel.add(newpass2Label);

        newpass2Field.setText("Current Password");
        newpass2Field.setToolTipText("Confirm New Password");
        newpass2Field.setPreferredSize(new java.awt.Dimension(250, 30));
        newpass2Panel.add(newpass2Field);

        inputPanel.add(newpass2Panel);

        emailPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        emailLabel.setText("Email Address");
        emailPanel.add(emailLabel);

        emailTextField.setText("user@gmail.com");
        emailTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        emailPanel.add(emailTextField);

        inputPanel.add(emailPanel);

        actionsPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        saveButton.setText("Save Changes");
        saveButton.setToolTipText("");
        actionsPanel.add(saveButton);

        cancelButton.setText("Cancel");
        actionsPanel.add(cancelButton);

        inputPanel.add(actionsPanel);

        getContentPane().add(inputPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileManageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField currentpassField;
    private javax.swing.JLabel currentpassLabel;
    private javax.swing.JPanel currentpassPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField newpass2Field;
    private javax.swing.JLabel newpass2Label;
    private javax.swing.JPanel newpass2Panel;
    private javax.swing.JPasswordField newpassField;
    private javax.swing.JLabel newpassLabel;
    private javax.swing.JPanel newpassPanel;
    private javax.swing.JButton profilepicButton;
    private javax.swing.JLabel profilepicLabel;
    private javax.swing.JPanel profilepicPanel;
    private javax.swing.JPanel profilepicPreview;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
