/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uptackomsai.chatupt.gui;

import com.google.gson.Gson;
import com.formdev.flatlaf.FlatDarkLaf;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import uptackomsai.chatupt.model.Request;
import uptackomsai.chatupt.model.User;
import uptackomsai.chatupt.utils.ImageLoader;

/**
 *
 * @author Lei
 */
public class ProfileManageFrame extends javax.swing.JFrame {
    String userID;
    /**
     * Creates new form ProfileFrame
     */
    public ProfileManageFrame() { // should pass the userID from the Mainframe
        setResizable(false);
        
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setTitle("Profile Settings");
        setLocationRelativeTo(null);
        
        // Dynamically get username of user
        try{
            Gson gson = new Gson();
            // Connect to the server and send registration request
            Socket socket = new Socket("localhost", 12345); // Assuming server is on localhost
            PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            // Create a update request message
            Request message = new Request("userData", null); // Use Message structure
            String jsonMessage = gson.toJson(message);

            // Send registration request to server
            out.println(jsonMessage);

            // Read response from server
            JsonObject jsonObject = JsonParser.parseString(in.readLine()).getAsJsonObject();
            userID = jsonObject.get("username").getAsString();

            // Close the connection
            socket.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to server: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        usernameTextField.setText(userID);
        
        profilepicLabel.setIcon(new ImageIcon(
            ImageLoader.loadImageIcon("default.png").getImage().getScaledInstance(
            profilepicLabel.getPreferredSize().width,
            profilepicLabel.getPreferredSize().height,
            Image.SCALE_SMOOTH)
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPanel = new javax.swing.JPanel();
        profilepicPanel = new javax.swing.JPanel();
        profilepicPreview = new javax.swing.JPanel();
        profilepicLabel = new javax.swing.JLabel();
        profilepicButton = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        currentpassLabel = new javax.swing.JLabel();
        currentpassField = new javax.swing.JPasswordField();
        newpassLabel = new javax.swing.JLabel();
        newpassField = new javax.swing.JPasswordField();
        newpass2Label = new javax.swing.JLabel();
        newpass2Field = new javax.swing.JPasswordField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        settingsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailNotifCheckbox = new javax.swing.JCheckBox();
        desktopNotifCheckbox = new javax.swing.JCheckBox();
        actionsPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        leftPadding = new javax.swing.JPanel();
        rightPadding = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        borderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borderPanel.setLayout(new java.awt.BorderLayout());

        profilepicPreview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profilepicPreview.setToolTipText("");
        profilepicPreview.setLayout(new java.awt.BorderLayout());

        profilepicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilepicLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        profilepicPreview.add(profilepicLabel, java.awt.BorderLayout.CENTER);

        profilepicButton.setText("Change");
        profilepicButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profilepicButton.setPreferredSize(new java.awt.Dimension(100, 23));
        profilepicButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        profilepicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilepicButtonActionPerformed(evt);
            }
        });
        profilepicPreview.add(profilepicButton, java.awt.BorderLayout.SOUTH);

        profilepicPanel.add(profilepicPreview);

        borderPanel.add(profilepicPanel, java.awt.BorderLayout.NORTH);

        inputPanel.setPreferredSize(new java.awt.Dimension(400, 420));
        inputPanel.setLayout(new java.awt.BorderLayout());

        center.setPreferredSize(new java.awt.Dimension(400, 420));
        center.setLayout(new java.awt.GridLayout(12, 0, 0, 5));

        usernameLabel.setText("Username");
        center.add(usernameLabel);

        usernameTextField.setEditable(false);
        usernameTextField.setText("Current Username");
        usernameTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(usernameTextField);

        currentpassLabel.setText("Current Password");
        center.add(currentpassLabel);

        currentpassField.setToolTipText("Enter Current Password");
        currentpassField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(currentpassField);

        newpassLabel.setText("New Password");
        center.add(newpassLabel);

        newpassField.setToolTipText("Enter New Password");
        newpassField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(newpassField);

        newpass2Label.setText("Confirm New Password");
        center.add(newpass2Label);

        newpass2Field.setToolTipText("Confirm New Password");
        newpass2Field.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(newpass2Field);

        emailLabel.setText("Email Address");
        center.add(emailLabel);

        emailTextField.setText("currentemail@gmail.com");
        emailTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(emailTextField);

        jLabel1.setText("Notifications");
        settingsPanel.add(jLabel1);

        emailNotifCheckbox.setSelected(true);
        emailNotifCheckbox.setText("Email");
        settingsPanel.add(emailNotifCheckbox);

        desktopNotifCheckbox.setText("Desktop");
        settingsPanel.add(desktopNotifCheckbox);

        center.add(settingsPanel);

        actionsPanel.setPreferredSize(new java.awt.Dimension(400, 50));
        actionsPanel.setLayout(new java.awt.BorderLayout());

        saveButton.setText("Save Changes");
        saveButton.setToolTipText("");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        actionsPanel.add(saveButton, java.awt.BorderLayout.EAST);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        actionsPanel.add(cancelButton, java.awt.BorderLayout.WEST);

        center.add(actionsPanel);

        inputPanel.add(center, java.awt.BorderLayout.CENTER);

        leftPadding.setPreferredSize(new java.awt.Dimension(80, 10));
        inputPanel.add(leftPadding, java.awt.BorderLayout.WEST);

        rightPadding.setPreferredSize(new java.awt.Dimension(80, 10));
        inputPanel.add(rightPadding, java.awt.BorderLayout.EAST);

        borderPanel.add(inputPanel, java.awt.BorderLayout.CENTER);

        footerPanel.setPreferredSize(new java.awt.Dimension(10, 30));
        borderPanel.add(footerPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(borderPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // update backend 
        // Create a JSON object for user registration
        Gson gson = new Gson();
        
        String username = usernameTextField.getText().trim();
        String currentPass = new String(currentpassField.getPassword()).trim();
        String password = new String(newpassField.getPassword()).trim();
        String confirmPassword = new String(newpass2Field.getPassword()).trim();
        String email = emailTextField.getText().trim();
        
        User user = new User(username, password, email);
        String userJson = gson.toJson(user);
        
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (currentPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Current password field is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            // Connect to the server and send registration request
            Socket socket = new Socket("localhost", 12345); // Assuming server is on localhost
            PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            // Create a update request message
            Request message = new Request("editProfile", userJson); // Use Message structure
            String jsonMessage = gson.toJson(message);

            // Send registration request to server
            out.println(jsonMessage);

            // Read response from server
            String response = in.readLine();
            JOptionPane.showMessageDialog(this, response, "Server Response", JOptionPane.INFORMATION_MESSAGE);

            // Close the connection
            socket.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to server: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void profilepicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilepicButtonActionPerformed
        // Choose a file to upload
        JFileChooser fileChooser = new JFileChooser();
        
        // Set up the file filter for image files
        FileFilter imageFilter = new FileFilter() {
            @Override
            public boolean accept(File file) {
                // Allow directories or files with specific image extensions
                if (file.isDirectory()) {
                    return true;
                }
                String fileName = file.getName().toLowerCase();
                return fileName.endsWith(".jpg") || fileName.endsWith(".jpeg") ||
                        fileName.endsWith(".png") || fileName.endsWith(".bmp");
            }
            @Override
            public String getDescription() {
                return "Image Files (*.jpg, *.jpeg, *.png, *.bmp)";
            }
        };

        // Set the filter to the file chooser
        fileChooser.setFileFilter(imageFilter);
        int returnVal = fileChooser.showOpenDialog(inputPanel);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            String fileName = selectedFile.getName();
            String filePath = selectedFile.getAbsolutePath();
            String url = selectedFile.toURI().toString();
            
            // Set the profile picture preview into the selectedFile
            
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image scaledImage = imageIcon.getImage().getScaledInstance(profilepicPreview.getWidth(), 
                    profilepicPreview.getHeight(), 
                    Image.SCALE_SMOOTH);
            profilepicLabel.setIcon(new ImageIcon(scaledImage));
        }
    }//GEN-LAST:event_profilepicButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        try {
            // Set the FlatLaf Look and Feel
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileManageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JPanel borderPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel center;
    private javax.swing.JPasswordField currentpassField;
    private javax.swing.JLabel currentpassLabel;
    private javax.swing.JCheckBox desktopNotifCheckbox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JCheckBox emailNotifCheckbox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftPadding;
    private javax.swing.JPasswordField newpass2Field;
    private javax.swing.JLabel newpass2Label;
    private javax.swing.JPasswordField newpassField;
    private javax.swing.JLabel newpassLabel;
    private javax.swing.JButton profilepicButton;
    private javax.swing.JLabel profilepicLabel;
    private javax.swing.JPanel profilepicPanel;
    private javax.swing.JPanel profilepicPreview;
    private javax.swing.JPanel rightPadding;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
