/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uptackomsai.chatupt.gui;


import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;
import uptackomsai.chatupt.model.Request;
import uptackomsai.chatupt.model.User;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import uptackomsai.chatupt.utils.ImageLoader;

/**
 *
 * @author Lei
 */
public class SignupFrame extends javax.swing.JFrame {
    private String serverHost = "192.168.137.1";
    /**
     * Creates new form SignupFrame
     */
    public SignupFrame(String serverHost) {
        this.serverHost = serverHost;
        setResizable(false);
        
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setTitle("Signup Form");
        setLocationRelativeTo(null);
        
        profilepicLabel.setIcon(new ImageIcon(
            ImageLoader.loadImageIcon("default.png").getImage().getScaledInstance(
            profilepicLabel.getPreferredSize().width,
            profilepicLabel.getPreferredSize().height,
            Image.SCALE_SMOOTH)
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPanel = new javax.swing.JPanel();
        profilepicPanel = new javax.swing.JPanel();
        profilepicPreview = new javax.swing.JPanel();
        profilepicLabel = new javax.swing.JLabel();
        profilepicButton = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        password2Label = new javax.swing.JLabel();
        password2Field = new javax.swing.JPasswordField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        actionsPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        leftPadding = new javax.swing.JPanel();
        rightPadding = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 400));

        borderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borderPanel.setLayout(new java.awt.BorderLayout());

        profilepicPreview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profilepicPreview.setToolTipText("");
        profilepicPreview.setLayout(new java.awt.BorderLayout());

        profilepicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilepicLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        profilepicPreview.add(profilepicLabel, java.awt.BorderLayout.CENTER);

        profilepicButton.setText("Change");
        profilepicButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profilepicButton.setPreferredSize(new java.awt.Dimension(100, 23));
        profilepicButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        profilepicPreview.add(profilepicButton, java.awt.BorderLayout.SOUTH);

        profilepicPanel.add(profilepicPreview);

        borderPanel.add(profilepicPanel, java.awt.BorderLayout.PAGE_START);

        inputPanel.setMinimumSize(new java.awt.Dimension(220, 315));
        inputPanel.setPreferredSize(new java.awt.Dimension(400, 315));
        inputPanel.setLayout(new java.awt.BorderLayout());

        center.setPreferredSize(new java.awt.Dimension(400, 315));
        center.setLayout(new java.awt.GridLayout(9, 1, 0, 5));

        usernameLabel.setText("Username");
        usernameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        center.add(usernameLabel);

        usernameTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(usernameTextField);

        passwordLabel.setText("Password");
        passwordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        center.add(passwordLabel);

        passwordField.setToolTipText("Enter Your Password");
        passwordField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(passwordField);

        password2Label.setText("Confirm Password");
        password2Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        center.add(password2Label);

        password2Field.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(password2Field);

        emailLabel.setText("Email Address");
        emailLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        center.add(emailLabel);

        emailTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        center.add(emailTextField);

        actionsPanel.setPreferredSize(new java.awt.Dimension(400, 50));
        actionsPanel.setLayout(new java.awt.BorderLayout());

        cancelButton.setText("Cancel Signup");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        actionsPanel.add(cancelButton, java.awt.BorderLayout.WEST);

        submitButton.setText("Submit Form");
        submitButton.setToolTipText("");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        actionsPanel.add(submitButton, java.awt.BorderLayout.EAST);

        center.add(actionsPanel);

        inputPanel.add(center, java.awt.BorderLayout.CENTER);

        leftPadding.setPreferredSize(new java.awt.Dimension(80, 10));
        inputPanel.add(leftPadding, java.awt.BorderLayout.WEST);

        rightPadding.setPreferredSize(new java.awt.Dimension(80, 10));
        inputPanel.add(rightPadding, java.awt.BorderLayout.EAST);

        borderPanel.add(inputPanel, java.awt.BorderLayout.CENTER);

        footerPanel.setPreferredSize(new java.awt.Dimension(10, 30));
        borderPanel.add(footerPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(borderPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        new LoginFrame().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        String username = usernameTextField.getText().trim();
        String password = new String(passwordField.getPassword()).trim();
        String confirmPassword = new String(password2Field.getPassword()).trim();
        String email = emailTextField.getText().trim();

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (username.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Create a JSON object for user registration
            Gson gson = new Gson();
            User user = new User(username, password, email);
            String userJson = gson.toJson(user);

            // Connect to the server and send registration request
            Socket socket = new Socket(serverHost, 12345); // Assuming server is on localhost
            PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            // Create a registration request message
            Request message = new Request("register", userJson); // Use Message structure
            String jsonMessage = gson.toJson(message);

            // Send registration request to server
            out.println(jsonMessage);

            // Read response from server
            String response = in.readLine();
            JOptionPane.showMessageDialog(this, response, "Server Response", JOptionPane.INFORMATION_MESSAGE);

            // Close the connection
            socket.close();

            if (response.equalsIgnoreCase("Registration successful.")) {
                this.dispose(); // Close the signup frame on success
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to server: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // create account backend
        new LoginFrame().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            // Set the FlatLaf Look and Feel
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupFrame("localhost").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JPanel borderPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel center;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel leftPadding;
    private javax.swing.JPasswordField password2Field;
    private javax.swing.JLabel password2Label;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton profilepicButton;
    private javax.swing.JLabel profilepicLabel;
    private javax.swing.JPanel profilepicPanel;
    private javax.swing.JPanel profilepicPreview;
    private javax.swing.JPanel rightPadding;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
